# Generated by Django 3.0.2 on 2020-01-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='survivor',
            name='items',
            field=models.ManyToManyField(to='general.Item', verbose_name='Itens'),
        ),
    ]
