# Generated by Django 3.0.2 on 2020-01-24 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_survivor_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survivor',
            name='items',
        ),
    ]
